service: serverless-nodejs

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
