service: serverless-nodejs

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ap-northeast-1

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  exclude:
    - migrations/**
    - node_modules/**
    - .dynamodb/**
    - .git/**

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    seed:
      development:
        sources:
          - table: users
            sources: [./migrations/users.json]

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
  users:
    handler: users.handler
    events:
      - http:
          path: /users
          method: get

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
